apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
    name: rekrutteringsbistand-stilling
    namespace: default
    labels:
        team: arbeidsgiver
spec:
    # prettier-ignore
    image: {{ image }}
    port: 8080
    replicas:
        min: 2
        max: 3
        cpuThresholdPercentage: 50
    prometheus:
        enabled: false
        path: /metrics
    liveness:
        initialDelay: 10
        path: /rekrutteringsbistand-stilling/internal/isAlive
    readiness:
        initialDelay: 10
        path: /rekrutteringsbistand-stilling/internal/isReady
    resources:
        limits:
            cpu: 500m
            memory: 256Mi
        requests:
            cpu: 200m
            memory: 128Mi
    ingresses:
        - https://rekrutteringsbistand.nais.adeo.no/rekrutteringsbistand-stilling
    env:
        - name: LOGIN_URL
          value: https://loginservice.nais.adeo.no/login
        - name: STILLING_API_URL
          value: https://arbeidsgiver.nais.adeo.no/rekrutteringsbistand-api
        - name: KANDIDAT_API_URL
          value: https://rekrutteringsbistand-kandidat-api.nais.adeo.no/rest
        - name: VIS_STILLING_URL
          value: https://www.nav.no/arbeid/stilling
