apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
    name: rekrutteringsbistand
    namespace: default
    labels:
        team: {{team}}
spec:
    image: {{version}}
    port: 8080
    replicas:
        min: 2
        max: 3
        cpuThresholdPercentage: 50
    prometheus:
        enabled: false
        path: /metrics
    liveness:
        initialDelay: 60
        path: /internal/isAlive
    readiness:
        initialDelay: 60
        path: /internal/isReady
    resources:
        limits:
            cpu: 500m
            memory: 256Mi
        requests:
            cpu: 200m
            memory: 128Mi
    ingresses:
        - https://rekrutteringsbistand.nais.preprod.local
        - https://pam-rekrutteringsbistand.nais.preprod.local
    env:
        - name: LOGIN_URL
          value: https://loginservice.nais.preprod.local/login
        - name: REKRUTTERINGSBISTAND_BASE_URL
          value: https://arbeidsgiver.nais.preprod.local/rekrutteringsbistand-api
        - name: REKRUTTERINGSBISTAND_API_URL
          value: https://arbeidsgiver.nais.preprod.local/rekrutteringsbistand-api/rekrutteringsbistand/api/v1/
        - name: REKRUTTERING_API_URL
          value: https://arbeidsgiver.nais.preprod.local/rekrutteringsbistand-api/rekruttering/
        - name: REKRUTTERINGSBISTAND_API_SEARCH_URL
          value: https://arbeidsgiver.nais.preprod.local/rekrutteringsbistand-api/search-api/
