apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
    name: rekrutteringsbistand-stilling
    namespace: default
    labels:
        team: arbeidsgiver
spec:
    # prettier-ignore
    image: {{ image }}
    port: 8080
    replicas:
        min: 2
        max: 3
        cpuThresholdPercentage: 50
    prometheus:
        enabled: false
        path: /metrics
    liveness:
        initialDelay: 10
        path: /stillinger/internal/isAlive
    readiness:
        initialDelay: 10
        path: /stillinger/internal/isReady
    resources:
        limits:
            cpu: 500m
            memory: 256Mi
        requests:
            cpu: 200m
            memory: 128Mi
    ingresses:
        - https://rekrutteringsbistand.nais.preprod.local/microfrontend-ressurser/stilling
    env:
        - name: LOGIN_URL
          value: https://loginservice.nais.preprod.local/login
        - name: REKRUTTERINGSBISTAND_BASE_URL
          value: https://arbeidsgiver.nais.preprod.local/rekrutteringsbistand-api
        - name: VIS_STILLING_URL
          value: https://www-q0.nav.no/arbeid/stilling
