apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-rekrutteringsbistand
  namespace: default
  labels:
    team: teampam
spec:
  image: repo.adeo.no:5443/pam-rekrutteringsbistand
  port: 8080
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
    path: /metrics
  liveness:
    initialDelay: 60
    path: /internal/isAlive
  readiness:
    initialDelay: 60
    path: /internal/isReady
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 128Mi
  ingresses:
    - https://pam-rekrutteringsbistand.nais.adeo.no
    - https://rekrutteringsbistand.nais.adeo.no
  env:
    - name: LOGIN_URL
      value: https://loginservice.nais.adeo.no/login
    - name: PAM_AD_API_BACKEND_REKRUTTERINGSBISTAND_URL
      value: https://pam-ad-api.nais.adeo.no/rekrutteringsbistand/api/v1/
    - name: PAMADAPIBACKENDSEARCH_URL
      value: https://pam-ad-api.nais.adeo.no/search-api/